class MatchResult:
    match: str
    start: int
    end: int

class TextSearch:
    def __init__(self, case: str, returns: str) -> None: ...
    def add(self, key: str | dict[str, str] | list[str], value: str | None = None) -> None: ...
    def replace(self, text: str) -> str: ...
    def findall(self, text: str) -> list[MatchResult]: ...

